- Puppetfile
- site-modules/profile/manifests/base.pp
This is being tested on glick-pup & glick-client01.
A duplicate of this PR was approved yesterday before this repo was rebuilt today. But thought I'd go through the PR motions to test the new repo configuration.
> ASDPLNG-105: Add puppet-profile_selinux to tag v0.1.0

- data/role/puppet_master.yaml
Rules in POSTROUTING:nat:IPv4 on LSST puppet server were getting
removed causing the container to lose network access.
The current list of ignores for that table+chain are not generic enough.
It will ignore rules that match "172.17", "172.18", "172.19"
but LSST was getting rules with 172.21, and there is no immediate
knowledge of why or how docker chooses these addresses
So need to loosen the matching so it will ignore any rule that matches
any of these regexes:
POSTROUTING:nat:IPv4:
- '-s 172\.'  # yamllint disable-line rule:quoted-strings
- '-d 172\.'  # yamllint disable-line rule:quoted-strings
Need to add the string in single quotes otherwise puppet will complain
as it tries to interpret the escape character and you get an error.
Our .yamllint.yaml sets strings to use double-quotes, …
> ASDPLNG-117 Edit ignores for POSTROUTING:nat:IPv4

- Puppetfile
profile_system_auth tag v0.2.0 switches to use `authselect` instead of `authconfig` as default for RedHat systems
> Update profile_system_auth to tag v0.2.0

- data/common.yaml
This reenables KerberosAuthentication by default in profile_allow_ssh_from_bastion.
Tested on `glick-pup`.
> update sssd parameters to work when no kerberos hostkey is created

- Puppetfile
- data/common.yaml
See https://jira.ncsa.illinois.edu/browse/SVC-3960
This was tested on the following hosts:
- glick-client01
This is mainly to merge over the changes from https://git.ncsa.illinois.edu/ici/asd/asd-pup-control/-/merge_requests/31
> SVC-3960: Fix Puppet agent monitoring

- Puppetfile
SECOPS-3307: Update root equivalence reporting script to use syslog
> Update ncsa/profile_audit to tag v0.1.3

- Puppetfile
This installs the perl dependency packages under Redhat for the root equivalence script. These were not getting installed by default under CentOS 7, so needed to specifically make sure they are installed.
> Update ncsa/profile_audit to tag v0.1.5

- Puppetfile
This is being tested on glick-client01.
The change to ncsa/profile_audit updates the k5login_otp_audit.pl to ignore empty lines (in addition to comments).
> Update ncsa/profile_audit to tag v0.1.6

- Puppetfile
- data/common.yaml
- site-modules/profile/manifests/redhat.pp
See https://jira.ncsa.illinois.edu/browse/ASDPLNG-152
This is being tested on:
- `glick-client01`
Note that because we are not setting the `rhsm` parameters, we get the following output on each puppet run:
> Notice: Missing org value
> Notice: /Stage[main]/Rhsm/Notify[Missing org value]/message: defined 'message' as 'Missing org value'
...which is fine -- it reminds a real control repo to get it setup.
> ASDPLNG-152: Add ncsa/rhsm module

- Puppetfile
See https://jira.ncsa.illinois.edu/browse/SVC-4463
Fixes https://github.com/ncsa/puppet-sssd/issues/3
This is being tested on:
- `glick-client01`
> SVC-4463: Update ncsa/sssd to tag v3.0.2

- Puppetfile
See https://jira.ncsa.illinois.edu/browse/ASDPLNG-221
This was temporarily tested on `asd-vault1`, but not currently in use there.
Currently no hosts managed by this control repo require this, but it was added for support of temporary testing of delta test hosts.
> ASDPLNG-221: Add ncsa/profile_nfs_client tag v0.1.0

- data/common.yaml
Set sssd auth_provider: "krb5"
Set createhost user as controlrepo
This is being tested on `control-pup01`
See: https://jira.ncsa.illinois.edu/browse/ASDPLNG-267
> ASDPLNG-267: Add vault secrets for control-repo

- Puppetfile
- data/common.yaml
Updating the puppet-profile_monitoring module to v0.1.8 to add
management support of the inventory collection script
Also updating these configs in data/common.yaml to allow the telegraf
user the permissions to run the HW inventory script:
profile_pam_access::allow_rules:
profile_sudo::configs:
> Update for puppet-profile_monitoring v0.1.8

- Puppetfile
See https://jira.ncsa.illinois.edu/browse/ASDPLNG-278
Summary:
- Include default setting for `RevokeKeys` in `sshd_config`
- Add comment to top of `sshd_config` about it being managed by Puppet
This is being tested on the following hosts:
- `control-pup01`
- `control-test01`
> ASDPLNG-278: Update ncsa/sshd to tag v0.3.4

- data/common.yaml
filter_groups: xdmod
filter_users: conserver, postgres, xdmod
See https://jira.ncsa.illinois.edu/browse/ASDPLNG-276
This is being tested on `control-pup01`.
> ASDPLNG-276: add entries to sssd filter_groups & filter_users

- Puppetfile
See:
- https://jira.ncsa.illinois.edu/browse/ASDPLNG-323
- https://github.com/ncsa/puppet-rhsm/issues/2
This was tested on `control-pup01` & `control-test01`.
> ASDPLNG-323: Update ncsa/rhsm to tag v0.1.3

- Puppetfile
Point profile_firewall to branch: rundall/ASDPLNG-625/allow_lo_ipv6. Will update to tag once that branch is merged.
> ASDPLNG-625 - allow access to default IPv6 localhost

- Puppetfile
NOTICE!
If you are using any of the following modules, make sure you are using
at least this tag version listed:
puppet-profile_allow_ssh_from_bastion v0.2.4
puppet-profile_hostbased_ssh v1.0.1
That is because those modules at that version explicitly set the
AuthenticationMethods xxx for the match blocks that they manage
If you have any other match blocks set via some other means be
sure they also set AuthenticationMethods appropriately, since
this update sets 'AuthenticationMethods none' globally each match
block needs to define what AuthenticationMethods it needs
> SECURITY-1421 Set "AuthenticationMethods none" in global sshd_config

- Puppetfile
See: https://jira.ncsa.illinois.edu/browse/SVC-20629
This is being tested on `control-test05` & `control-test06`.
> SVC-20629: Upgrade ncsa/profile_motd to tag v0.2.0

- Puppetfile
Adds knockout_prefix for telegraf::inputs and telegraf::outputs in hiera
> SVC-20620 Update ncsa/puppet-telegraf to v3.1.2

- data/site/private.yaml
Fix #87 
See https://jira.ncsa.illinois.edu/browse/SVCPLAN-1236
This is being tested on `control-test-centos7a` & `control-test06` (RHEL 8.6).
> SVCPLAN-1236: Update site private to use http protocol for yum proxy

- data/common.yaml
[RHEL8+ incorporated tracefs for tracing](https://access.redhat.com/solutions/5914171). We want the `control-repo` default to exclude `tracefs`
> SVCPLAN-1107: ignore tracefs in telegraf's inputs.disk

- data/common.yaml
inputs.io was deprecated in telegraf version 0.10.0 and will be removed in 2.0.0
The measurement on influxdb side was already named diskio so no changes needed on
grafana panels
Also setup diskio to only monitor certain devices:
sd* and vd*
ignoring devices like: dm-0, loop*, etc
> SVCPLAN-1556 - telegraf input use inputs.diskio instead of inputs.io

- Puppetfile
Fix fact 'rhsm_manage_repo' for Centos hosts
> SVCPLAN-1587 Update puppet-rhsm from v0.1.6 to v0.1.7

- Puppetfile
See https://jira.ncsa.illinois.edu/browse/SVCPLAN-1633
This has been tested on the following hosts:
```
control-test-centos7a
control-test-rhel7a
control-test-rhel84a
control-test-rhel8a
control-test-rhel9a
```
> SVCPLAN-1633: Update ncsa/profile_user_environment to tag v0.1.2

- site-modules/profile/manifests/base.pp
- site-modules/profile/manifests/redhat.pp
Takes the Puppet class re-ordering work Bill setup in Holli and moves
that into the redhat.pp profile
The re-ordering work speeds up Puppet runs so that yum repos and packages
are setup before other classes that depend on them try and fail due to
missing dependencies
Moving this logic into redhat.pp doesn't change the behavior, just
moves it to a location specific for RHEL family hosts
> SVCPLAN-1649 Set Puppet Class relationships

- data/common.yaml
profile::sssd::enablemkhomedir: true
->
profile_system_auth::config::enable_mkhomedir: true
profile::sssd does not exist (anymore?); change to profile_system_auth::config instead.
This is effectively a no-op because this param defaults to in the profile_system_auth.
But I tested on these two machines:
control-test-rhel84b
control-test-rhel9b
> profile::sssd::enablemkhomedir -> profile_system_auth::config::enable_mkhomedir

- Puppetfile
This adds an optional method to disable some unbound settings related to DNSSEC
As-is does not change default behavior
> SECURITY-1502 Update profile_dns_cache to v1.1.3

- Puppetfile
use profile_slurm v1.2.0
1.1.6 -> 1.1.7 — tested on HOLL-I
1.1.7 -> 1.2.0 — tested (profile_slurm::crons, the only thing that changed from 1.1.7 to 1.2.0) on control-test-rhel84b.internal.ncsa.edu
> SVCPLAN-1695: update profile_slurm

- Puppetfile
Instead of using tidy resource, create a cron that deletes old reports.
Have tested on control-pup01 for a while, also dt-conf01 (not the Puppet part here, but had manually implemented the cron a while ago).
> SVCPLAN-629: improve tidy class

- Puppetfile
This change was tested with `linux-test` in the `asd-control` repo.
> SVC-22397: Update ncsa/profile_duo to tag v1.0.5

- Puppetfile
This fixes a bug where the lustre module was sometimes getting installed before configuration in place.
This has been tested in the control repo used by ticket SVCPLAN-2550 but can not currently be tested on any test nodes that actually use `control-repo`.
> SVCPLAN-2550: Upgrade ncsa/profile_lustre to tag v1.4.3

- Puppetfile
This is being tested on:
-     control-test-centos7a
-     control-test-rhel7a
-     control-test-rhel8a
-     control-test-rhel9a
> SVCPLAN-2112: Update ncsa/profile_audit to tag v0.1.14

- Puppetfile
Tested on mgsched2 via mg-pup01. Also tested that r10k can build the environment on control-pup01, and tested running control-test-rhel84b.internal.ncsa.edu against that environment (although it doesn't use profile_mysql_server).
> SVCPLAN-2680: update profile_mysql_server to v0.1.1

- Puppetfile
Change will remove setuid bit from /usr/bin/fusermount3.
Tested on control-test-rhel8b (after manual install of fuse3) and mgtest01.
> SVCPLAN-2364: update profile_hardening to v0.3.2

- Puppetfile
profile_postgres_server is being used in Nightingale on ng-db*, so the code has been tested there.
For adding to control-repo, I've added to the Puppetfile and run r10k, and tested control-test-rhel84b.internal.ncsa.edu on this environment (without it actually using profile_postgres_server).
> SVCPLAN-339: add profile_postgres_server

- Puppetfile
See https://jira.ncsa.illinois.edu/browse/SECURITY-1497
We need to optionally allow hosts within a cluster to relay SMTP traffic.
This was tested on `control-test-rhel8a`.
- `control-test-rhel86a` was temporarily setup to relay through `control-test-rhel8a`.
> SECURITY-1497: Upgrade ncsa/profile_email to tag v0.2.4

- Puppetfile
This has been tested on:
- control-test-rhel7a
- control-test-rhel8a
- control-test-rhel9a
> SVCPLAN-2926: Upgrade ncsa/telegraf to tag ncsa/v0.1.1

- Puppetfile
This pulls in an update to profile_lustre. Note that the only update there is in the README, although I did make sure that r10k runs on control-pup01 and that a couple of test clients can get a catalog from that environment (and a no-op Puppet run).
> SVCPLAN-3012: update profile_lustre to v1.4.4

- Puppetfile
See commit message in module for some possible cleanup tasks
> SVCPLAN-2993 Update puppet-sshd from v0.4.1 to v0.5.0

- Puppetfile
This has been tested on `control-test-rhel7b`, `control-test-rhel8b`, & `control-test-rhel9b`.
> SVCPLAN-794: Update ncsa/profile_timesync to tag v0.2.2

- data/common.yaml
Preparing for removal of `org_asd` LDAP group.
This is being tested on: 
```
control-test-centos7b
control-test-rhel7b
control-test-rhel86b
control-test-rhel9a
```
This will require some manual cleanup of `sshd_config`, & `access.conf` after the update.
> SVCPLAN-3691: Replace usage of org_asd group for access after ASD reorg

- Puppetfile
This has been tested on:
```
control-test-centos7a
control-test-rhel7a
control-test-rhel8a
control-test-rhel8b
control-test-rhel8c
control-test-rhel9b
```
> Update ncsa/profile_update_os to tag v0.4.2

- Puppetfile
This adds the nfs4-acl-tools to all NFS clients, which allows for viewing and modifying NFSv4 ACLs.
> SVCPLAN-2009: update profile_nfs_client to v0.2.0

- Puppetfile
Docs-only change, but tested r10k and noop in control-repo and mg-control.
> SVCPLAN-3252: update profile_puppet_agent to v0.1.4

- Puppetfile
Introduces rsyslog configuration to watch gridftp.log and modifies logrotate configuration to notify rsyslog when this log is rotated.
> SVCPLAN-2747: update profile_globus to v0.5.2

- Puppetfile
Fixes https://github.com/ncsa/puppet-profile_motd/issues/9
This has been tested extensively in `asd-pup-control`.
> SVCPLAN-3996: Upgrade ncsa/motd to tag v0.3.2 - issue9-etcmotdd-broken-for-user-root

- Puppetfile
- data/common.yaml
This is being tested in control-repo on the following hosts:
```
control-test-centos7a
control-test-centos7b
control-test-rhel7a
control-test-rhel7b
control-test-rhel8a
control-test-rhel8b
control-test-rhel9a
control-test-rhel9b
```
> SVCPLAN-3972: Unify local telegraf uid

- Puppetfile
See commit notes in module since some hosts may need manual cleanup
> SVCPLAN-2290 Update puppet-profile_audit from v0.1.15 to v0.1.16

- Puppetfile
Update profile_monitoring from v0.3.0 to v0.3.2 so that RO RHEL 9 systemd mounts are included in KNOWN_RO_MOUNTS in mount-state.sh and are ignored.
> SVCPLAN-4538: update KNOWN_RO_MOUNTS for telegraf to ignore

- Puppetfile
This adds the ability to startup unbound with the DISABLE_UNBOUND_ANCHOR="yes" option for use in cases where the DNS servers do not support DNSSEC.
This has been tested on:
- control-test-rhel88b
- control-test-rhel9b
> SVCPLAN-3995: Upgrade ncsa/profile_dns_cache to tag v1.1.4

- Puppetfile
- data/common.yaml
These newer module versions are supposed to work with Slurm v22.05 & v23.02 (in addition to v23.11) but we have not tested with them.
Also pin CgroupPlugin to "cgroup/v1" until we test cgroups-v2.
> SVCPLAN-5026: module updates for Slurm v23.11 support

- Puppetfile
Only send backup CRON emails on error
This has been tested on `control-pup01`.
> SVCPLAN-5040: Upgrade ncsa/profile_backup to tag v0.0.9

- data/common.yaml
This has been tested on the following hosts:
- control-test-centos7b
- control-test-rhel7b
- control-test-rhel8b
- control-test-rhel9b
> SVCPLAN-4719: Use sec_ops_vet group for IRST vetting access

- Puppetfile
This has been tested on `control-pup01`.
> SVCPLAN-5450: Upgrade ncsa/profile_update_os to tag v0.4.3
