ncsa/control-repo

Puppetfile
SVC-1601: remove setuid bit from ksu binary
=> Update profile_system_auth to tag v0.3.0

Puppetfile, data/role/log_collector.yaml, site-modules/role/manifests/log_collector.pp
- Add log_collector role
- Update profile_rsyslog to tag v0.1.4
Mirroring over rsyslog improvements from https://jira.ncsa.illinois.edu/browse/SVC-100
=> SVC-100: Add log_collector role, update profile_rsyslog to tag v0.1.4

Puppetfile, data/common.yaml, data/role/puppet_master.yaml, site-modules/profile/manifests/base.pp
See https://jira.ncsa.illinois.edu/browse/ASDPLNG-125
All updates are disable via hiera
=> ASDPLNG-125: Add profile_update_os tag v0.2.0

Puppetfile
Add some default packages for RedHat family
https://jira.ncsa.illinois.edu/browse/SVC-3596
=> SVC-3596: Update profile_additional_packages to tag v0.3.0

Puppetfile
This is being tested on `glick-pup` & `glick-client01`.
=> Update ncsa/profile_audit to tag v0.1.4

Puppetfile
Update profile_dns_cache to v1.1.1
=> SECURITY-1324 Update profile_dns_cache to v1.1.1

Puppetfile
ASDPLNG-325 - Block all_disabled_usr in access.conf
=> ASDPLNG-325 Update puppet-profile_pam_access to v0.0.6

data/common.yaml
See https://jira.ncsa.illinois.edu/browse/ASDPLNG-422
This has been being tested on the following hosts since Feb 1:
```
control-test05
control-test06
```
=> ASDPLNG-422: Update sssd to use OU for group & user search base

Puppetfile
This sets up a method to disable su, which is disabled by default
=> SECURITY-1401 Update profile_system_auth to v0.3.8

Puppetfile, data/common.yaml
See https://jira.ncsa.illinois.edu/browse/ASDPLNG-453
This is being tested on `control-test06`.
=> ASDPLNG-453: Update ncsa/profile_update_os to tag v0.3.7

data/common.yaml, hiera.yaml
see: https://jira.ncsa.illinois.edu/browse/ASDPLNG-572
this is being tested on:
```
bsper2-pupclient
control-pup01
control-test01
control-test02
control-test03
control-test04
control-test05
control-test06
```
=> ASDPLNG-572: Switch vault hiera to use token auth

Puppetfile, site-modules/profile/manifests/base.pp
See https://jira.ncsa.illinois.edu/browse/ASDPLNG-615
This is being tested on `control-pup`.
=> ASDPLNG-615: Add ncsa/profile_hardening tag v0.1.0

Puppetfile, site-modules/profile/manifests/base.pp
See https://jira.ncsa.illinois.edu/browse/ASDPLNG-598
This is being tested on `control-pup01`.
I plan to go ahead and merge this around late morning today.
=> ASDPLNG-598: Add ncsa/profile_user_environment tag v0.1.0

Puppetfile, site-modules/profile/manifests/base.pp
Add a new ncsa/networking module
For now it just has a script for monitoring mellanox cards/cables via
TIG
But will eventually hold any custom networking configs we need
=> SVCPLAN-1534 Add ncsa/networking - just TIG mellanox for now

Puppetfile
Add profile_java v0.1.0 to Puppetfile (but do not add to any roles in this upstream control-repo).
=> SVCPLAN-2367: add profile_java to Puppetfile

Puppetfile, data/common.yaml
This is being tested on `control-test-rhel8a`
=> Update ncsa/profile_motd to tag v0.3.0

Puppetfile
Enhance node state information gathered by check
=> SVCPLAN-3008 Enhance node_state reporting

Puppetfile
@ncsa/asd Please review as time permits.
=> SVCPLAN-3318 Fix quoting causing parse issue

Puppetfile
@ncsa/asd Please review for merge that updates Slurm module version from 1.5.1 to 1.5.2
=> Fix Slurm metrics parsing bugs

Puppetfile
This adds a script to configure/manage audits of xcat nodes
=> CTA-259 Update ncsa/puppet-profile_xcat to v1.1.9

Puppetfile
@ncsa/asd Please review; I updated the Slurm version from 1.6.1 to 1.6.2
=> SVCPLAN-3864 Fixed parse bug for per-user resource usage

Puppetfile
Doc updates, pdk update/validate.
=> SVCPLAN-3831: update profile_postgres_server to v0.1.1

Puppetfile
@ncsa/asd Please review, updating module version of puppet-profile_gpu
=> Updated for new GPU module version, enhanced DCGM changes
